# Generated by Django 4.1.7 on 2023-02-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(upload_to='media/products')),
                ('Offer_price', models.CharField(max_length=50)),
                ('Original_price', models.CharField(max_length=50)),
                ('Quantities', models.IntegerField()),
                ('Description', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=50)),
                ('Added_At', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.categories')),
            ],
        ),
    ]
