# Generated by Django 4.1.7 on 2023-02-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
