# Generated by Django 4.1.7 on 2023-02-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0003_user_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_date',
            new_name='User_data',
        ),
    ]
