# Generated by Django 4.1.7 on 2023-02-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0004_rename_user_date_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Color', models.CharField(max_length=20)),
                ('Cart_price', models.IntegerField()),
                ('Cart_total_price', models.IntegerField()),
                ('Added_at', models.DateTimeField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.products')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.user_data')),
            ],
        ),
    ]
