# Generated by Django 4.1.7 on 2023-03-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0007_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('Added_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Color', models.CharField(max_length=20)),
                ('Cart_price', models.IntegerField()),
                ('Cart_total_price', models.IntegerField()),
                ('Order_id', models.CharField(max_length=50)),
                ('Added_at', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.user_data')),
            ],
        ),
    ]
